# DataCamp course on TensorFlow
[Link](https://campus.datacamp.com/courses/introduction-to-tensorflow-in-python/63343?ex=1)

In [1]:
import tensorflow as tf

In [30]:
from tensorflow import fill, constant, ones_like, multiply
from tensorflow import Variable
from tensorflow import matmul, subtract, reduce_sum
from tensorflow import ones, reshape
from tensorflow import GradientTape

In [47]:
import numpy as np
import pandas as pd

A constant is the simplest category of tensor. It can't be trained, which makes it a bad choice for a model's parameters, but a good choice for input data. Input data may be transformed after it is defined or loaded, but is typically not modified by the training process.

In [11]:
# Define a 3x4 tensor with all values equal to 9
x = fill([3, 4], 9)

# Define a tensor of ones with the same shape as x
y = ones_like(x)

# Define the one-dimensional vector, z
z = constant([1, 2, 3, 4])

In [12]:
# Print z as a numpy array
print(z.numpy())

[1 2 3 4]


Unlike a constant, a variable's value can be modified. This will be quite useful when we want to train a model by updating its parameters. Constants can't be used for this purpose, so variables are the natural choice.

In [13]:
# Define the 1-dimensional variable X
X = Variable([1, 2, 3, 4])

# Print the variable X
print(X)

# Convert X to a numpy array and assign it to Z
Z = X.numpy()

# Print Z
print(Z)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>
[1 2 3 4]


In later chapters, you will make use of constants and variables to train models. Your datasets will be represented as constant tensors of type tf.Tensor() or numpy arrays. The model's parameters will be represented by variables that are updated during computation.

Element-wise multiplication in TensorFlow is performed using two tensors with identical shapes. 

In [14]:
# Define tensors A0 and B0 as constants
A0 = constant([1, 2, 3, 4])
B0 = constant([[1, 2, 3], [1, 6, 4]])

# Define A1 and B1 to have the correct shape
A1 = ones_like(A0)
B1 = ones_like(B0)

# Perform element-wise multiplication
A2 = multiply(A0, A1)
B2 = multiply(B0, B1)

# Print the tensors A2 and B2
print(A2.numpy())
print(B2.numpy())

[1 2 3 4]
[[1 2 3]
 [1 6 4]]


In later chapters, you will learn to train linear regression models. This process will yield a vector of parameters that can be multiplied by the input data to generate a vector of predictions. I

In [16]:
# Define X, b, and y as constants
X = constant([[1, 2], [2, 1], [5, 8], [6, 10]])
b = constant([[1], [2]])
y = constant([[6], [4], [20], [23]])

# Compute ypred using X and b
ypred = matmul(X, b)

# Compute and print the error as y - ypred
error = subtract(y, ypred)
print(error.numpy())

[[ 1]
 [ 0]
 [-1]
 [-3]]


You've been given a matrix, wealth. This contains the value of bond and stock wealth for five individuals. Note that this is given in thousands of dollars.

The first row corresponds to bonds and the second corresponds to stocks. Each column gives the stock and bond wealth for a single individual. Use wealth, reduce_sum(), and .numpy() to determine which statements are correct about wealth

In [18]:
wealth = constant([[11, 7, 4, 3, 25], [50, 2, 60, 0, 10]])

In [19]:
wealth

<tf.Tensor: id=57, shape=(2, 5), dtype=int32, numpy=
array([[11,  7,  4,  3, 25],
       [50,  2, 60,  0, 10]], dtype=int32)>

In [25]:
# Column sums
reduce_sum(wealth, 0)

<tf.Tensor: id=67, shape=(5,), dtype=int32, numpy=array([61,  9, 64,  3, 35], dtype=int32)>

In [26]:
# Row sums
reduce_sum(wealth, 1)

<tf.Tensor: id=70, shape=(2,), dtype=int32, numpy=array([ 50, 122], dtype=int32)>

Combined, the 5 individuals hold $50,000 in bonds.

In many machine learning problems, you will need to reshape your input data

In [28]:
# Define input image
image = ones([16, 16])

# Reshape image into a vector
image_vector = reshape(image, (256, 1))

# Reshape image into a higher dimensional tensor
image_tensor = reshape(image, (4, 4, 4, 4))

Adapt image by adding three color channels and then adjust image_vector and image_tensor accordingly.



In [29]:
# Add three color channels
image = ones([16, 16, 3])

# Reshape image into a vector
image_vector = reshape(image, (768, 1))

# Reshape image into a higher dimensional tensor
image_tensor = reshape(image, (4, 4, 4, 4, 3))

### Optimizing with gradients
You are given a loss function, y=x2, which you want to minimize. You can do this by identifying points where the slope is zero using the GradientTape() operation. Gradient descent selects an initial value for x and then iterates until it finds an x that corresponds to a gradient of zero.

In practice, you will use a high level tensorflow operation to perform gradient descent automatically. In this exercise, however, you will simply guess that the minimum is at x=0 and then verify by computing the gradient.

In [31]:
# Define x as a variable equal to 0.0
x = Variable(0.0)

# Define y using the multiply operation and apply Gradient Tape
with GradientTape() as tape:
    tape.watch(x)
    y = multiply(x, x)

# Compute the gradient of y with respect to x
g = tape.gradient(y, x)

# Compute and print the gradient using the numpy method
print(g.numpy())

0.0


### Performing graph-based computations
You are given a black-and-white image of a letter, which has been encoded as a tensor, letter. You want to determine whether the letter is an X or a K. You don't have a trained neural network, but you do have a simple model, model, which can be used to classify letter.

The 3x3 tensor, letter, and the 1x3 tensor, model, are available in the Python shell. You can determine whether letter is an X by multiplying letter by model, summing over the result, and then checking if it is equal to 1. As with more complicated models, such as neural networks, model is a collection of weights, arranged in a tenso

In [42]:
model = constant([1., 0., -1.])
letter = constant([[1., 0., 1.], [1., 1., 0.], [1., 0., 1.]])

In [43]:
# Reshape model from a 1x3 to a 3x1 tensor
model = reshape(model, (3, 1))

# Multiply letter by model
output = matmul(letter, model)

# Sum over output and print prediction using the numpy method
prediction = reduce_sum(output, 0)
print(prediction.numpy())

[1.]


When performing operations in tensorflow, you will need to ensure that your choice of data types is valid. For example, let's say you're using the housing['price'] column from the King County dataset to define the constant tensor, price. You then want to multiply that tensor by a constant, scalar. Given the definitions below, how can you define price to ensure that scalar, price, and adjusted_price have the same data type?

Before you can train a machine learning model, you must first import data. There are several valid ways to do this, but for now, we will use a simple one-liner from pandas: pd.read_csv(). Recall from the video that the first argument specifies the path or URL. All other arguments are optional.

In this exercise, you will import the King County housing dataset, which we will use to train a linear model later in the chapter.

In [54]:
housing = pd.read_csv("https://assets.datacamp.com/production/repositories/3953/datasets/818cd72f8f36fb710e52074a41b0cfd322915eaa/kc_house_data.csv")

In [55]:
scalar = tf.constant(0.1, tf.float32)
price = np.array(housing['price'], np.float32)
adjusted_prices = tf.multiply(price, scalar)

In [57]:
# This would also work
price = tf.cast(housing['price'], tf.float32)

In [58]:
# Import numpy and tensorflow with their standard aliases
import numpy as np
import tensorflow as tf

# Use a numpy array to define price as a 32-bit float
price = np.array(housing['price'], np.float32)

# Define waterfront as a Boolean using cast
waterfront = tf.cast(housing['waterfront'], tf.bool)

# Print price and waterfront
print(price)
print(waterfront)

[221900. 538000. 180000. ... 402101. 400000. 325000.]
tf.Tensor([False False False ... False False False], shape=(21613,), dtype=bool)


Notice that printing price yielded a numpy array; whereas printing waterfront yielded a tf.Tensor()

https://campus.datacamp.com/courses/introduction-to-tensorflow-in-python/63343?ex=5